// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datagrabber.proto

package dgproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchReq struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c794cd1986f2f27b, []int{0}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DataHeaderResp struct {
	ColHeader            string   `protobuf:"bytes,1,opt,name=ColHeader,proto3" json:"ColHeader,omitempty"`
	RowHeader            string   `protobuf:"bytes,2,opt,name=RowHeader,proto3" json:"RowHeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataHeaderResp) Reset()         { *m = DataHeaderResp{} }
func (m *DataHeaderResp) String() string { return proto.CompactTextString(m) }
func (*DataHeaderResp) ProtoMessage()    {}
func (*DataHeaderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c794cd1986f2f27b, []int{1}
}

func (m *DataHeaderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataHeaderResp.Unmarshal(m, b)
}
func (m *DataHeaderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataHeaderResp.Marshal(b, m, deterministic)
}
func (m *DataHeaderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataHeaderResp.Merge(m, src)
}
func (m *DataHeaderResp) XXX_Size() int {
	return xxx_messageInfo_DataHeaderResp.Size(m)
}
func (m *DataHeaderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DataHeaderResp.DiscardUnknown(m)
}

var xxx_messageInfo_DataHeaderResp proto.InternalMessageInfo

func (m *DataHeaderResp) GetColHeader() string {
	if m != nil {
		return m.ColHeader
	}
	return ""
}

func (m *DataHeaderResp) GetRowHeader() string {
	if m != nil {
		return m.RowHeader
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchReq)(nil), "dgproto.SearchReq")
	proto.RegisterType((*DataHeaderResp)(nil), "dgproto.DataHeaderResp")
}

func init() {
	proto.RegisterFile("datagrabber.proto", fileDescriptor_c794cd1986f2f27b)
}

var fileDescriptor_c794cd1986f2f27b = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x49, 0x2c, 0x49,
	0x4c, 0x2f, 0x4a, 0x4c, 0x4a, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f,
	0x49, 0x07, 0x33, 0x94, 0xb4, 0xb9, 0x38, 0x83, 0x53, 0x13, 0x8b, 0x92, 0x33, 0x82, 0x52, 0x0b,
	0x85, 0xe4, 0xb8, 0xb8, 0x3c, 0x53, 0x52, 0xf3, 0x4a, 0x32, 0xd3, 0x32, 0x53, 0x8b, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x94, 0x7c, 0xb8, 0xf8, 0x5c, 0x12, 0x4b, 0x12, 0x3d,
	0x52, 0x13, 0x53, 0x52, 0x8b, 0x82, 0x52, 0x8b, 0x0b, 0x84, 0x64, 0xb8, 0x38, 0x9d, 0xf3, 0x73,
	0x20, 0x02, 0x50, 0x0d, 0x08, 0x01, 0x90, 0x6c, 0x50, 0x7e, 0x39, 0x54, 0x96, 0x09, 0x22, 0x0b,
	0x17, 0x30, 0xf2, 0xe6, 0xe2, 0x06, 0x99, 0x16, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64,
	0x03, 0xe1, 0x7a, 0xe6, 0x15, 0x96, 0x66, 0x16, 0x55, 0x0a, 0x09, 0xe9, 0x41, 0x9d, 0xa8, 0x07,
	0x77, 0x9f, 0x94, 0x38, 0x5c, 0x0c, 0xd5, 0x19, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0x71, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x69, 0x7f, 0x37, 0xec, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	DataInquiry(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (DataService_DataInquiryClient, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) DataInquiry(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (DataService_DataInquiryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataService_serviceDesc.Streams[0], "/dgproto.DataService/DataInquiry", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataServiceDataInquiryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataService_DataInquiryClient interface {
	Recv() (*DataHeaderResp, error)
	grpc.ClientStream
}

type dataServiceDataInquiryClient struct {
	grpc.ClientStream
}

func (x *dataServiceDataInquiryClient) Recv() (*DataHeaderResp, error) {
	m := new(DataHeaderResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	DataInquiry(*SearchReq, DataService_DataInquiryServer) error
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) DataInquiry(req *SearchReq, srv DataService_DataInquiryServer) error {
	return status.Errorf(codes.Unimplemented, "method DataInquiry not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_DataInquiry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).DataInquiry(m, &dataServiceDataInquiryServer{stream})
}

type DataService_DataInquiryServer interface {
	Send(*DataHeaderResp) error
	grpc.ServerStream
}

type dataServiceDataInquiryServer struct {
	grpc.ServerStream
}

func (x *dataServiceDataInquiryServer) Send(m *DataHeaderResp) error {
	return x.ServerStream.SendMsg(m)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dgproto.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataInquiry",
			Handler:       _DataService_DataInquiry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "datagrabber.proto",
}
